version: '3.8'

services:
  postgres:
    image: postgres:13.0
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev
      POSTGRES_HOST: postgres
      POSTGRES_DB: api
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./tmp/db:/var/lib/postgresql/
  api:
    depends_on:
      - postgres
    build:
      context: ./
      dockerfile: ./api/Dockerfile
    volumes:
      - ./api/:/api:cached
      - bundle:/usr/local/bundle:cached
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    restart: always
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
volumes:
  bundle: